### ISSUE TITLE
[Bug Report] Automatic Version increase overwrite the version from all crates in cargo.lock

### ISSUE THREAD

**Issue by AmmarAbouZor** [kevinmatthes/aeruginous-rs#390]
While using the new feature to increase the version manually [Commit link](https://github.com/AmmarAbouZor/tui-journal/commit/20414952cc29369b4083083091db8fbcf36d8417) I ran to the issue that not only the version of my app has been overwritten, but also all the crates with a version matching the current version of my app.

I assume that the tool makes a search and replacement through the whole file which caused this problem. I'll suggest using TOML parser to replace the version in the app section only

**Comment by kevinmatthes** [comment]
Brilliant idea!  I will make this a special sub-mode for the version incrementing!

**Comment by kevinmatthes** [comment]
@AmmarAbouZor

I added the basic functionality to make this feature work:  the main `Cargo.toml` will be updated using the TOML parser of the `toml` crate and the main `Cargo.lock` will be updated using the `cargo-lock` crate *if* the package name is given.  I need to do some refinements but it already works properly.  If I am done with the polishing, I will release this feature as a patch since this functionality has a rather high priority.

Please tell me what should happen if the parsers should not be able to edit the files:  shall the files be edited with the normal logic (editing *any* matching version string), shall the files be skipped, or shall Aeruginous exit with an error condition?

**Comment by AmmarAbouZor** [comment]
Thanks for working on this. It should work the best with cargo-lock since the Cargo.lock file is too complicated for basic editing.

> Please tell me what should happen if the parsers should not be able to edit the files: shall the files be edited with the normal logic (editing any matching version string), shall the files be skipped, or shall Aeruginous exit with an error condition?

At this case I would suggest aborting the Version increasing step only and printing out a warning in the pipeline if this is possible (Printing a normal text can be enough though). In this case the maintainer will still get the CHANGELOG changes and  can approve on the PR then increase the version manually in a separated commit. or they can increase the version in the PR itself manually.

Editing the file with the old logic could produce errors and leaving the file untouched even though the version has been increased in the Cargo.toml would lead to some problems, since the Repo will left in a state that can't be compiled

**Comment by kevinmatthes** [comment]
@AmmarAbouZor

Thank you for your feedback!  I suggested something similar in #413, I only need to add the warning messages.  If you should find any other things I should change, please let me know.

I would like to suggest to continue this discussion in #413 to have all information on this feature in one place.
